version: 2.1

jobs:
  test:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - run:
          name: Install PDM
          command: pip install pdm
      - run:
          name: Install Dependencies
          command: pdm install --group test
      - run:
          name: Run Tests
          command: pdm run test

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.9", "3.10", "3.11", "3.12"]
